# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI/CD Pipeline with Github Actions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: eslint check
      run: npm run lint  --max-warnings 0
  
  tests:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: npm install
    - name: vite tests
      run: npm run test -- --passWithNoTests
      continue-on-error: false
  
  build:
    runs-on: ubuntu-latest
    needs: [lint, tests]
    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'

    - name: Install Dependencies
      run: npm install

    - name: Build Project
      run: npm run build
      continue-on-error: false

  deploy:
    runs-on: ubuntu-latest
    needs: [build, lint, tests]
    steps:
    - name: Deploy to Vercel
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      run: npx vercel --prod --yes --token $VERCEL_TOKEN
